### PR TITLE
Use music-metadata instead of jsmediatags to support tags better

### LINKED ISSUE #20: Media tags not working for FLAC files
Thanks for adding media tags support! 👍 

But unfortunately, they do not seem to work for FLAC files, even though jsmediatags says it supports it.

### PR DESCRIPTION
**Pull request by Shadester**
Fixes #20 

I have tested it and it seems to be working. A little caveat, I'm no TS / node developer and I'm not entirely sure how the async / await things work, so it might need some tweaks.

### CODE REVIEW

**Review by cybercase — CHANGES_REQUESTED** [review]
Hello @Shadester and thanks for your PR.

I've done a quick review and I found a few things that we might want to change before merging this PR. I've left a few comments here and there for you. Let me know if anything's unclear.

Thanks

**Comment by Shadester** [comment]
Thanks for the comments, will change it later today!

**Comment by cybercase** [comment]
@Shadester I've merged your PR into master and I'll try to deploy everything later today. Thanks for the help!

**Comment by Shadester** [comment]
@cybercase Thank you! I tested it with multiple formats and also a couple of FLACs that wouldn't work before, so I hope it works great. Thanks for the constructive comments, too.

**Pull request merged**
