### PR TITLE
Asivery's work on groups and full width titles

### PR DESCRIPTION
**Pull request by cybercase**

### CODE REVIEW

**Comment by cybercase** [comment]
Hello @asivery and thanks again for your impressive work.
The support for groups, the new drag&drop to rearrange the tracks, and the support for the full-width are really a great addition to the app. Your work will make a lot of users really happy, and I can't wait to merge :)

I'd like to discuss some minor things with you before proceeding.

**New Group Icon**
If you agree, I'd like to replace the _new group icon_
Screenshot 2021-07-18 at 11 58 13
with the Material Design `CreateNewFolder` icon.
Screenshot 2021-07-18 at 11 58 38

**Full Width Title Editing**
I trust you that this is working fine with units that supports full width titls. I've tried with my mz-n710 and I haven't been able to see any kanji or hiragana character on the unit's display. It just keeps displaying the title from the half-width slot.
Do you know if this is ok? Should I be able to see any full width characters?

By the way, I'd like to ask if you think it could be ok to just set the same value for both the slots at the same time. In this way we could get rid of both the second input field and the toggle button in the menu. It would be less confusing, especially for the less tech-savvy users.

Or maybe we could check if the title set by the user contains some full-width characters and the automatically pick which slot should we use.

Any other idea to avoid showing a second input field?

Screenshot 2021-07-18 at 12 11 58

**Comment by asivery** [comment]
Replacing the icon is a good idea - it makes it clearer that clicking it will create a group.
As for the full width slot - its contents are only displayed on some Japanese players and remotes (models ending with 'K'). I don't think there's a good way to merge the 2 fields into one. Some people might prefer changing the half-width slot independently of the full-width one. 
I added the toggle in the menu so that non tech-savvy people can just disable the full-width functionality in general.

**Comment by asivery** [comment]
Also, I fixed one bug in a commit I pushed yesterday, it's a one-line-fix, I think it's also worth merging. I sent you more info regarding the bug in an email.

**Comment by is-that-a-thing-now** [comment]
I am not sure if my comments are wanted or not, but I did a bunch of testing with @asivery on this with some Japanese hardware, and speak a little bit of Japanese so I think I understand the intended usage.

> I've tried with my mz-n710 and I haven't been able to see any kanji or hiragana character on the unit's display. It just keeps displaying the title from the half-width slot. Do you know if this is ok? Should I be able to see any full width characters?

No, the device screen is too low resolution, so it will only display the half-width titles.  More on this later.

>By the way, I'd like to ask if you think it could be ok to just set the same value for both the slots at the same time. In this way we could get rid of both the second input field and the toggle button in the menu. It would be less confusing, especially for the less tech-savvy users.

So this is the whole reason why there are two slots.  The half-width slot supports romaji (english letters) and half-width katakana (stuff like this "ｶﾀｶﾅ").  The half-width titles are easily displayed on low resolution screens, like the device screen.  Even if there is a full-width title, this half-width title will be used on any low rez screens (often the players themselves), non-kanji capable remotes, and non-kanji capable devices.

The full-full width slot supports kanji (this stuff: 漢字) full-width katakana (looks like this: カタカナ) and full-width hiragana (this: ひらがな). This is displayed on higher resolution screens (like a decks screen or a remote screen) and is the only way to display Kanji.

If you want to keep Kanji support, it seems necessary to have the two entries.  The half-width serves as a backup for the full-width slot, supplying the reading and still giving you the track name on any player that doesn't support kanji.

> Or maybe we could check if the title set by the user contains some full-width characters and the automatically pick which slot should we use.

This would work.  But if it chose the full-width slot, for example, places where the half-width would usually be displayed will just show nothing.  That is why during testing I suggested using SonicStage's default entry mode.  It defaults to half-width, but if you select full-width for entry, it will still try to fill the half-width slot with the non-kanji characters in order to have something there ("漢字テスト" in the full-width slot becomes  "  ﾃｽﾄ" in the half-width, each kanji was replaced with a space, and all instances of full-width katakana/hiragana are converted to half-width katakana). It actually overrides any titles you already have in the half-width slot, which is pretty annoying if you forget and do them out of order.

>Any other idea to avoid showing a second input field?

I really liked the solution @asivery came up with.  He set it so the interface defaulted to just half-width title entry, which is what most users will use. A check box in the settings was necessary to be able to input full-width titles. Those who intend to use Kanji will be the only ones who have to deal with the two entry slots.

**Comment by cybercase** [comment]
> I am not sure if my comments are wanted or not, but I did a bunch of testing with @asivery on this with some Japanese hardware, and speak a little bit of Japanese so I think I understand the intended usage.
> 

They are very welcome, and also, thanks for helping with testing.

> So this is the whole reason why there are two slots. The half-width slot supports romaji (english letters) and half-width katakana (stuff like this "ｶﾀｶﾅ"). The half-width titles are easily displayed on low resolution screens, like the device screen. Even if there is a full-width title, this half-width title will be used on any low rez screens (often the players themselves), non-kanji capable remotes, and non-kanji capable devices.
> 
> The full-full width slot supports kanji (this stuff: 漢字) full-width katakana (looks like this: カタカナ) and full-width hiragana (this: ひらがな). This is displayed on higher resolution screens (like a decks screen or a remote screen) and is the only way to display Kanji.

Ok, I didn't know how this worked exactly. Now it's clear.

> I really liked the solution @asivery came up with. He set it so the interface defaulted to just half-width title entry, which is what most users will use. A check box in the settings was necessary to be able to input full-width titles. Those who intend to use Kanji will be the only ones who have to deal with the two entry slots.

Ok, since most of the users won't have to deal with this, let's try with the double input field solution. I just fear it might be confusing to someone who doesn't know how this works (I was confused myself until now).
Maybe we could add a short explanation in the _Support and Faq_ page.

**Comment by cybercase** [comment]
> Also, I fixed one bug in a commit I pushed yesterday, it's a one-line-fix, I think it's also worth merging. I sent you more info regarding the bug in an email.

Sure, I'll definitely merge it.

**Comment by cybercase** [comment]
Merged!
Actually I couldn't reproduce the bug, but looking at the changes it shouldn't be a big deal.

I'm starting now to review the code. Apart from a couple of formatting issues (quickly fixed by running prettier) I'm confident that everything will be OK. I've tried the app and everything looks stable, and the drag&drop feature is really convenient.

Give me a couple of days at most to make sure everything is in order, then I think we can merge it.

**Comment by asivery** [comment]
Alright, if there's anything else you'd like to know, please message me.

**Comment by asivery** [comment]
> Actually I couldn't reproduce the bug
When you select a track and click on the rename icon (not doubleclick the track name), then change the track name, and confirm with Enter(not the rename button), the dialog will close, and then instantly reopen with the old track name.

**Comment by cybercase** [comment]
@asivery I've reviewed all the changes and made some minor adjustments. Great job!
Would you like to review my changes and let me know if everything's ok?
Then we can finally merge and deploy... and let the real testing begin :)

**Comment by asivery** [comment]
@cybercase Looks great! Thank you for such a fast code review. Let's see how many bugs people find :)

**Pull request merged**
